//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoeKing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pictures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pictures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineShoeKing.Resources.Pictures", typeof(Pictures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/aboutPic.jpg.
        /// </summary>
        public static string AboutPic {
            get {
                return ResourceManager.GetString("AboutPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/.
        /// </summary>
        public static string DefaultShoeImgFrom {
            get {
                return ResourceManager.GetString("DefaultShoeImgFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/home-slides/slides/.
        /// </summary>
        public static string DefaultShoeImgTo {
            get {
                return ResourceManager.GetString("DefaultShoeImgTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noImage.jpg.
        /// </summary>
        public static string DefaultSlideImg {
            get {
                return ResourceManager.GetString("DefaultSlideImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UsersImages/.
        /// </summary>
        public static string FolderUsersImages {
            get {
                return ResourceManager.GetString("FolderUsersImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/UsersImages/
        /// </summary>
        public static string FolderUsersImagesNoSlash {
            get {
                return ResourceManager.GetString("FolderUsersImagesNoSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/home-slides/slides/.
        /// </summary>
        public static string HomeSlides {
            get {
                return ResourceManager.GetString("HomeSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/home-slides/temp-slides/.
        /// </summary>
        public static string HomeSlidesTemp {
            get {
                return ResourceManager.GetString("HomeSlidesTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \images\home-slides\temp-slides\.
        /// </summary>
        public static string HomeSlidesTempLeftSlash {
            get {
                return ResourceManager.GetString("HomeSlidesTempLeftSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/orderImage.png.
        /// </summary>
        public static string OrderImage {
            get {
                return ResourceManager.GetString("OrderImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/images/products/.
        /// </summary>
        public static string PhotoInAdminPanel {
            get {
                return ResourceManager.GetString("PhotoInAdminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/products/.
        /// </summary>
        public static string PhotoPathProducts {
            get {
                return ResourceManager.GetString("PhotoPathProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/picGirl.png.
        /// </summary>
        public static string PicGirl {
            get {
                return ResourceManager.GetString("PicGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/picMen.png.
        /// </summary>
        public static string PicMen {
            get {
                return ResourceManager.GetString("PicMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/picPeople.png.
        /// </summary>
        public static string PicPeople {
            get {
                return ResourceManager.GetString("PicPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/picProducts.ico.
        /// </summary>
        public static string PicProducts {
            get {
                return ResourceManager.GetString("PicProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/cover.jpg.
        /// </summary>
        public static string ProfileCover {
            get {
                return ResourceManager.GetString("ProfileCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/profilePic.jpg.
        /// </summary>
        public static string ProfilePic {
            get {
                return ResourceManager.GetString("ProfilePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /images/profilePicWoman.jpg.
        /// </summary>
        public static string ProfileWoman {
            get {
                return ResourceManager.GetString("ProfileWoman", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to /images/about/about1.jpg.
        /// </summary>
        public static string AboutPicFirst
        {
            get
            {
                return ResourceManager.GetString("AboutPicFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to /images/about/about2.jpg.
        /// </summary>
        public static string AboutPicSecond
        {
            get
            {
                return ResourceManager.GetString("AboutPicSecond", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to /images/about/
        /// </summary>
        public static string AboutFolder
        {
            get
            {
                return ResourceManager.GetString("AboutFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to banner.jpg
        /// </summary>
        public static string HomePagePicture
        {
            get
            {
                return ResourceManager.GetString("HomePagePicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to /images/home-page/
        /// </summary>
        public static string HomePageImage
        {
            get
            {
                return ResourceManager.GetString("HomePageImage", resourceCulture);
            }
        }
        
    }
}
